COMPONENT_ADD_INCLUDEDIRS=spiffs/src
COMPONENT_SRCDIRS=spiffs/src
COMPONENT_ADD_INCLUDEDIRS+=./
COMPONENT_ADD_INCLUDEDIRS+=spiffs/src/test
CFLAGS	+= -DCONFIG_BUILD_SPIFFS
CFLAGS += -DSPIFFS_OBJ_META_LEN=0
CFLAGS += -DSPIFFS_TEMPORAL_FD_CACHE=1
